name: CI

on: [push, pull_request]

jobs:

  build-win:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6.x'

    - name: Setup venv
      run: |
        python -m venv venv
        . .\venv\Scripts\activate.ps1
        pip install -r requirements.txt

    - name: Build
      run: |
        . .\venv\Scripts\activate.ps1
        fbs freeze
        Compress-Archive -Path "target\QMK-Tools" -DestinationPath qmk-tools.zip

    - uses: actions/upload-artifact@v1
      with:
        name: QMK-Tools
        path: qmk-tools.zip
